### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by lloreleine** [ALapp18/AppKms#5]
Use personal account
// Google Connect / Facebook Connect ?

**Comment by arnaudmorisset** [comment]
Can I propose Auth0? https://auth0.com/

I think it's currently the best solution **which have a free tiers** with following features:

* 7,000 free active users & unlimited logins
* Passwordless & TouchID Login
* Lock for Web, iOS & Android
* Up to 2 social identity providers
* Unlimited Serverless Rules
* Community Support

and it can be easily replaced if another all-in-one solution appear.

**Comment by lloreleine** [comment]
Sure you can! ;)
